name: telos
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  flutter_deep_linking: ^0.2.1
  uni_links: ^0.5.1
  webview_flutter: ^4.7.0
  firebase_messaging: ^14.7.16
  flutter_local_notifications: ^16.3.2
  firebase_dynamic_links: ^5.3.5
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.8.7
  path_provider: ^2.1.2
  webview_flutter_android: ^3.15.0
  webview_flutter_wkwebview: ^3.12.0
  liquid_pull_to_refresh: ^3.0.1
  flutter_share: ^2.0.0
  share_plus: ^7.2.2
  flutter_document_picker: ^5.2.3
  fluttertoast: ^8.2.4
  firebase_crashlytics: ^3.4.15
  firebase_remote_config: ^4.3.15


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.2
  # path_provider: ^2.1.2
  # webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
